---
abstract: 'send email to groups'
author:
  - 'Alister West, C<< <alister at alisterwest.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-TicketPDF
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.1.1
